package vocal;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JOSAFAT
 */
import java.applet.*;//libreria para el sonido
public class Vocales extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Vocales
     */
    //decalramos los variables
    String[] texto;///para el arreglo de vocales
    
    int n;//para conteo
    boolean b = true;//para que el funcione el pause y iniciar
    private Thread hilo;//para el hilo
   
    public Vocales() {
        initComponents();
         this.setLocationRelativeTo(null);
         texto = new String[5];//para que sea 5 arreglos
         cargarVocales();//cargamos el metodo de vocales
         n=0;//para que el conteo empieza de cero
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Vocal = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnPausar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vocales");

        Vocal.setFont(new java.awt.Font("Tahoma", 1, 150)); // NOI18N
        Vocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vocal.setText("A");

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnPausar.setText("Pausar");
        btnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnPausar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Vocal, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Vocal, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPausar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        if(hilo == null){
            hilo = new Thread(this);
            hilo.start();
            
        }
       
        b = true;
        btnPausar.setEnabled(true);
        btnIniciar.setEnabled(false);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausarActionPerformed
       
        b = false;
        btnPausar.setEnabled(false);
        btnIniciar.setEnabled(true);
        
    }//GEN-LAST:event_btnPausarActionPerformed

    /**
     * @param args the command line arguments
     */   
    public static void main(String args[]) {
       new Vocales().setVisible(true);
            
    }
    //metodo de cargar vocales 
    private void cargarVocales(){
        //el empieza desde cero hasta llegar al 4
        texto[0] = "A";
        texto[1] = "E";
        texto[2] = "I";
        texto[3] = "O";
        texto[4] = "U";
         
        
    }
    ///metodo run
    @Override
    public void run() {
        //c = 1;
        ///////////////para agregar sonido
            AudioClip sound;
            sound = java.applet.Applet.newAudioClip(getClass().getResource("/vocal/vocal.wav"));//la ruta de la musica
            
                  try {
            sound.play();///reproduce el sonido
            
            
        } catch (Exception e) {
            
        }
            
        while(true){
            System.out.println("hilo ejecutado");
            if(b){
                //sound.play();
          
              //  Vocal.setText(texto[n]);
              ///condicion para que el contador llegue a 4
               if(n<=4){
                Vocal.setText(texto[n]);
              // sound.play();
                n++;
               
           // sound.loop();
             
            }else 
               
                n=0;
            }
            try{
              
                hilo.sleep(500);
            }catch(Exception e){
               System.out.println("error");
            }
        }
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Vocal;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPausar;
    // End of variables declaration//GEN-END:variables
}
